apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c --chart
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: authservice
  name: authservice
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
      nodePort: 30080
  selector:
    io.kompose.service: authservice
