apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c --chart
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: authservice
  name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authservice
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c --chart
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: authservice
    spec:
      containers:
        - image: vicky54/authenticationservice:latest
          imagePullPolicy: Always
          name: authservice
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
