apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c --chart
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c --chart
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: kafka
    spec:
      containers:
        - env:
            - name: ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: LOG_RETENTION_HOURS
              value: "1"
          image: krisgeus/docker-kafka
          name: kafka
          ports:
            - containerPort: 9092
              protocol: TCP
      restartPolicy: Always
