apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c --chart
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: persistentservice
  name: persistentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: persistentservice
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c --chart
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: persistentservice
    spec:
      containers:
        - image: vicky54/persistentservice:latest
          imagePullPolicy: Always
          name: persistentservice
      restartPolicy: Always
