apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c --chart
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: socketservice
  name: socketservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: socketservice
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c --chart
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: socketservice
    spec:
      containers:
        - env:
            - name: KAFKA_HOST
              value: kafka:9092
          image: vicky54/websocketservice:latest
          imagePullPolicy: Always
          name: websocketservice
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
